UPSTREAM: Fix version guard for cudaDevAttrHostNumaMemoryPoolsSupported (#7838)
cudaDevAttrHostNumaMemoryPoolsSupported was introduced in CUDA 12.9,
not 12.6. The incorrect _CCCL_CTK_AT_LEAST(12, 6) guard causes
compilation failures on CUDA 12.6-12.8 where the enum does not exist
in driver_types.h.

Fixes build error:
  error C2039: 'cudaDevAttrHostNumaMemoryPoolsSupported': is not a
  member of 'global namespace'

Introduced in #7339 (c0a03de8b).

(cherry picked from commit 6e17982b131d83d8400a1ce7f93a81465ca4129f)