Fix `CMAKE_CUDA_FLAGS`
@senior-zero found that we now have some undefined symbols in our build due to incorrect `CMAKE_CUDA_FLAGS`

> test_warp_load.cu:57: undefined reference to `__pgiLaunchKernelFromStub'
> /usr/bin/ld: /home/gevtushenko/src/senior-zero/cub/test/mersenne.h:157: undefined reference to `__cudaRegisterFunction'

Move the `-cuda` configuration back to the `CMAKE_CUDA_FLAGS`