[Internal Cleanup] pre-commit ruff libcudacxx/tests (#3152)
* Remove libcudacxx/test/ from ruff exclude list.

* ruff auto-fixes (NO manual changes).

* ruff --unsafe-fixes auto-fixes (NO manual changes).

* All manual fixes in one commit.

* Change BaseException to RuntimeError

Resolves this error:

https://github.com/NVIDIA/cccl/actions/runs/12307470549/job/34351208457?pr=3152

```
lit: C:\Python\lib\site-packages\lit\TestingConfig.py:152: fatal: unable to parse config file 'C:\\cccl\\libcudacxx\\test\\libcudacxx\\lit.cfg', traceback: Traceback (most recent call last):
  File "C:\Python\lib\site-packages\lit\TestingConfig.py", line 140, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "C:\cccl\libcudacxx\test\libcudacxx\lit.cfg", line 52, in <module>
    configuration.configure()
  File "C:\cccl\libcudacxx\test\utils\libcudacxx\test\config.py", line 215, in configure
    self.configure_cxx()
  File "C:\cccl\libcudacxx\test\utils\libcudacxx\test\config.py", line 364, in configure_cxx
    self.cxx = CXXCompiler(
  File "C:\cccl\libcudacxx\test\utils\libcudacxx\compiler.py", line 66, in __init__
    self._initTypeAndVersion()
  File "C:\cccl\libcudacxx\test\utils\libcudacxx\compiler.py", line 100, in _initTypeAndVersion
    macros = self.dumpMacros()
  File "C:\cccl\libcudacxx\test\utils\libcudacxx\compiler.py", line 419, in dumpMacros

    raise BaseException("Cannot be dumped on old MSVC")

BaseException: Cannot be dumped on old MSVC
```

(cherry picked from commit 836f769a4b4125fdc499a7941431b0fc7f00916a)