UPSTREAM: Avoid symbol clash with older clang (#5874)
Clang sometimes has issues with clashing symbols of different kind, e.g
```
error: redefinition of 'iter_swap' as different kind of symbol
```

To avoid that extend the workaround for clang-16 to all older clang.

Fixes nvbug5517623

(cherry picked from commit 765d25a4caa2a41eb97ca9a6f6c4b692d824d062)